apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tnsrnats.frontenac.tech
spec:
  group: frontenac.tech
  names:
    kind: tnsrNAT
    plural: tnsrnats
    singular: tnsrnat
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: tnsrNAT is a definition used by the tnsr-controller to establish the configuration options for tnsr ACLs and NAT rules that need
        to be created to allow external (Internet) access to a service. This resource should generally only be spawned by a service
        using the tnsr.frontenac.tech/tnsrACL annotation.
        type: object
        properties:
          spec:
            description: tnsrNAT.spec represents the desired state for the NAT rule (and associated ACL rule) which is to be applied in tnsr.
            type: object
            properties:
              externalPort:
                type: integer
              localPort:
                type: integer
              natInt:
                type: string
              localIP:
                type: string
              protocol:
                type: string
              tnsrACL:
                type: string
          status:
            description: tnsrNAT.status outlines the status of the generated NAT and ACL rules in TNSR. This will give basic information about
            the creation status of the ACL and NAT rules.
            type: object
            properties:
              nat_created:
                type: boolean
              acl_rule_created:
                type: boolean
              acl_rule_sequence:
                type: integer
              acl_info: # Result of `show acl {acl_name}`
                type: string
              error:
                type: string
