name: Create Development Build
on: [push, workflow_dispatch]
jobs:
  build-publish-image:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: registry.frontenac.tech
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.frontenac.tech/fts/tnsr-controller:latest,registry.frontenac.tech/fts/tnsr-controller:dev-${{ github.sha }}